---
apiVersion: v1
kind: Service
metadata:
  name: larsenfarm
  labels:
    app: larsenfarm
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: larsenfarm
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: larsenfarm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: larsenfarm
    spec:
      containers:
      - name: larsenfarm
        image: larsenfarm
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: larsenfarm-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/tls-acme: 'true'
spec:
  tls:
  - hosts:
      - larsenfarm.qchsag.ca
    secretName: larsenfarm.qchsag.ca
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: larsenfarm
          servicePort: 80
    host: larsenfarm.qchsag.ca
